#index:
#    path: /
#    controller: App\Controller\DefaultController::index
lbc__adds_list:
  path: /
  controller: App\Controller\HomeController::getAllAdds
  methods:  [GET]
  options:
    expose: true

lbc__adds_add:
  path: /add-add
  controller:   App\Controller\HomeController::addAddAction
  methods:  [POST]
  options:
    expose: true